import os

RISK_ALLOCATION = 0.50
DELTA_MIN = 0.12 
DELTA_MAX = 0.30
YIELD_MIN = 0.05
YIELD_MAX = 1.00
EXPIRATION_MIN = 35
EXPIRATION_MAX = 55
OPEN_INTEREST_MIN = 100
SCORE_MIN = 0.05

# --- ADVANCED RISK FILTERS ---
MAX_BID_ASK_SPREAD = 1.50   # Hard cap in dollars
MAX_RELATIVE_SPREAD = 0.15  # Dynamic cap (15% of option value)
MAX_SPREADS_PER_SYMBOL = 1
MAX_NEW_TRADES_PER_CYCLE = 8

# 0.98 means we ask for 98% of the mid-price (giving the market maker 2% incentive to fill us).
SLIPPAGE_ALLOWANCE = 0.0  
# SLIPPAGE_ALLOWANCE = 1.0: Purely dynamic (trusts the bot 100%).

# SLIPPAGE_ALLOWANCE = 0.90: Makes the bot 10% more aggressive to get fills.

# SLIPPAGE_ALLOWANCE = 1.10: Makes the bot 10% greedier (demands better prices).

AVOID_EARNINGS = True
MAX_RISK_PER_SPREAD = 1000.0  
PROFIT_TARGET = 0.50  
STOP_LOSS = 3.0

# --- FUND DASHBOARD SETTINGS ---

# 1. Discord Alerts (set DISCORD_WEBHOOK_URL in your .env — see .env.example)
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL", "")

# 2. Idle Cash Sweep
SWEEP_TICKER = "SGOV"  # SGOV = 0-3 Month Treasury Bill ETF (~5.3% Yield)
TARGET_CASH_BUFFER = 1000.0 # Always keep at least $1,000 in pure cash for daily settlements

# 3. Dynamic VIX Risk Scaling
MAX_RISK_BASE = 1000.0 # Your standard risk when VIX is normal

# 4. Signal Quality Guardrails
# Avoid forcing full deployment when the directional models disagree or are weak.
MIN_SIGNAL_CONFIDENCE = 0.18
LOW_CONFIDENCE_RISK_MULTIPLIER = 0.50
MIN_EXECUTABLE_TRADE_RISK = 100.0
MIN_EXECUTABLE_TRADE_RISK_PCT_EQUITY = 0.025

# 5. HMM pairs mean-reversion overlay
ENABLE_PAIRS_TRADING = True
PAIR_MAX_SIGNALS = 6
PAIR_ENTRY_ZSCORE = 1.5
PAIR_LOOKBACK_DAYS = 120
PAIR_MIN_CORRELATION = 0.65
PAIR_MIN_CONFIDENCE = 0.55

# 6. Execution quality / TCA knobs
TCA_SPREAD_WEIGHT = 0.65
TCA_SLIPPAGE_WEIGHT = 0.25
TCA_LIQUIDITY_WEIGHT = 0.10

# 6B. Delay-aware option repricing controls
OPTION_QUOTE_DELAY_MINUTES = 15
OPTION_PRICING_RISK_FREE_RATE = 0.04
OPTION_DELAY_MIN_PRICING_CONFIDENCE = 0.32
OPTION_DELAY_MAX_UNDERLYING_MOVE_PCT = 0.035
OPTION_DELAY_QUOTE_HAIRCUT = 0.06

# 6C. Limit-order fill monitoring and quant reprice controls
ORDER_MONITOR_ENABLED = True
ORDER_MONITOR_POLL_SECONDS = 5
ORDER_MONITOR_TIMEOUT_SECONDS = 45
ORDER_MONITOR_MAX_REPRICES = 3
ORDER_MONITOR_REPRICE_FRACTION = 0.35
ORDER_MONITOR_MIN_PRICE_STEP = 0.02
ORDER_MONITOR_VAR_CONFIDENCE = 0.95
ORDER_MONITOR_VAR_HORIZON_DAYS = 1.0
ORDER_MONITOR_MC_PATHS = 2000

# 6CA. Portfolio-wide Monte Carlo risk guardrails
PORTFOLIO_RISK_ENGINE_ENABLED = True
PORTFOLIO_RISK_HISTORY_CACHE_SECONDS = 1800
PORTFOLIO_RISK_CONFIDENCE = 0.95
PORTFOLIO_RISK_HORIZON_DAYS = 1.0
PORTFOLIO_RISK_MC_PATHS = 2500
PORTFOLIO_RISK_STUDENT_T_DF = 5
PORTFOLIO_RISK_MAX_VAR_PCT_EQUITY = 0.065
PORTFOLIO_RISK_MAX_CVAR_PCT_EQUITY = 0.085
PORTFOLIO_RISK_MAX_STRESS_PCT_EQUITY = 0.12
PORTFOLIO_RISK_MAX_SINGLE_UNDERLYING_WEIGHT = 0.38
PORTFOLIO_RISK_MAX_CORRELATION_CONCENTRATION = 0.58
PORTFOLIO_RISK_MAX_GROSS_EXPOSURE_PCT_EQUITY = 2.50
PORTFOLIO_RISK_HARD_KILL_DAILY_PNL_PCT = -10.0
PORTFOLIO_RISK_HARD_KILL_CVAR_PCT_EQUITY = 0.11
PORTFOLIO_RISK_HARD_KILL_STRESS_PCT_EQUITY = 0.15

# 6D. Cross-sectional ML alpha controls
ML_ALPHA_ENABLED = True
ML_ALPHA_MAX_SYMBOLS = 48
ML_ALPHA_MIN_TRAIN_MONTHS = 48
ML_ALPHA_CACHE_MAX_AGE_MINUTES = 240
ML_ALPHA_TOP_PERCENTILE = 0.80
ML_ALPHA_BOTTOM_PERCENTILE = 0.20

# 7. Platinum-mode portfolio sizing controls
PLATINUM_MODE = True
TARGET_DAILY_RETURN_GOAL = 0.05  # Stretch target; not a guarantee.
MAX_KELLY_FRACTION = 0.35

# 8. Direct equity overlay controls
ENABLE_EQUITY_OVERLAY = True
EQUITY_OVERLAY_MAX_ALLOCATION = 0.12
EQUITY_OVERLAY_MAX_POSITIONS = 4
EQUITY_OVERLAY_MAX_SYMBOL_WEIGHT = 0.04
EQUITY_OVERLAY_MIN_SIGNAL = 0.62
EQUITY_OVERLAY_EXIT_SIGNAL = 0.52
EQUITY_OVERLAY_MIN_EXPECTED_MOVE = 0.0005
EQUITY_OVERLAY_PROFIT_TARGET = 0.08
EQUITY_OVERLAY_STOP_LOSS = 0.05
EQUITY_OVERLAY_MAX_VIX = 26.0

# 9. Direct equity event / IV / distribution filters
EQUITY_OVERLAY_EVENT_WINDOW_DAYS = 10
EQUITY_OVERLAY_MAX_EVENT_CANDIDATES = 8
EQUITY_OVERLAY_MAX_IV_RANK = 80.0
EQUITY_OVERLAY_IV_FLOOR_RANK = 30.0
EQUITY_OVERLAY_MAX_IV_REALIZED_RATIO = 1.35
EQUITY_OVERLAY_MAX_DISTRIBUTION_ZSCORE = 1.8
EQUITY_OVERLAY_EVENT_BOOST = 0.08

# 10. Stock-based delta hedge overlay
ENABLE_DELTA_HEDGE_OVERLAY = True
DELTA_HEDGE_LONG_SYMBOL = "SPY"
DELTA_HEDGE_INVERSE_SYMBOL = "SH"
DELTA_HEDGE_MAX_ALLOCATION = 0.08
DELTA_HEDGE_MIN_GAP = 20.0
DELTA_HEDGE_SCALING = 0.75
DELTA_HEDGE_MAX_VIX = 32.0

# 11. Cornwall convexity sleeve
CORNWALL_MAX_ALLOCATION_PCT = 0.03
CORNWALL_MAX_PRICE_PER_LEG = 0.30
CORNWALL_MIN_PRICE_PER_LEG = 0.05
CORNWALL_MIN_DTE = 90
CORNWALL_MAX_DTE = 180
CORNWALL_MAX_VOL_RANK = 15.0
CORNWALL_MAX_SPREAD = 0.15
CORNWALL_MIN_PRICING_CONFIDENCE = 0.45
CORNWALL_MIN_MODEL_EDGE = 0.02
CORNWALL_MIN_TAIL_PAYOFF_MULTIPLE = 6.0
CORNWALL_MIN_FAT_TAIL_PROBABILITY = 0.02
CORNWALL_MIN_STRIKE_DISTANCE_PCT = 0.05
CORNWALL_MAX_STRIKE_DISTANCE_PCT = 0.35
CORNWALL_MONTE_CARLO_PATHS = 4000
CORNWALL_MAX_TRADES_PER_RUN = 4

# 11b. Asymmetric Bets Engine (rebuilt 2026-07-18)
# Only takes setups with a DEFINED max loss and payoff >= ASYM_MIN_RATIO x
# that loss; sizes each bet so the worst case is a known slice of equity.
ENABLE_ASYMMETRIC_ENGINE = True
ASYM_MIN_RATIO = 4.0            # min target-gain / max-loss to take a bet
ASYM_TOTAL_RISK_PCT = 0.06      # max 6% of equity at risk across all engine bets
ASYM_PER_BET_RISK_PCT = 0.015   # max 1.5% of equity risked on any single bet
ASYM_OPTION_BUDGET_FRACTION = 0.35  # share of remaining risk budget for option tails
ASYM_TIME_STOP_DAYS = 45        # calendar-day time stop for R-positions

# 12. Deep-value (Graham net-net) sleeve
# Nightly scan of daily movers for stocks priced below net current asset value.
# NOT risk-free: daily-loser lists are full of value traps, hence the quality
# gates and hard caps below.
ENABLE_DEEP_VALUE = True
DEEP_VALUE_AUTO_EXECUTE = True          # False = scan + alert only, no buys
DEEP_VALUE_MAX_ALLOCATION = 0.20        # sleeve cap as fraction of total equity
DEEP_VALUE_MAX_SYMBOL_WEIGHT = 0.05     # per-name cap as fraction of total equity
DEEP_VALUE_MAX_POSITIONS = 5
DEEP_VALUE_MARGIN_OF_SAFETY = 0.66      # buy only if price < 0.66 x NCAV/share (Graham)
DEEP_VALUE_MIN_PRICE = 1.00             # avoid delisting-track penny stocks
DEEP_VALUE_MIN_MARKET_CAP = 50e6
DEEP_VALUE_MIN_DOLLAR_VOLUME = 2e6      # avg daily $ volume floor
DEEP_VALUE_MIN_RUNWAY_QUARTERS = 4      # cash burn runway floor (FCF-positive passes)
DEEP_VALUE_EXCLUDED_SECTORS = ("Financial Services", "Real Estate")  # NCAV meaningless
DEEP_VALUE_TARGET_NCAV_FRACTION = 0.90  # take profit when price re-rates to 90% of entry NCAV
DEEP_VALUE_STOP_LOSS = 0.30             # hard stop on unrealized loss
DEEP_VALUE_MAX_HOLD_DAYS = 120          # time stop (calendar days)
DEEP_VALUE_SCAN_MAX_AGE_HOURS = 20      # last night's scan valid through next close
DEEP_VALUE_ALERT_SCORE = 0.70           # Discord alert threshold
DEEP_VALUE_MIN_ENTRY_SCORE = 0.35       # floor for auto-entries
