RISK_ALLOCATION = 0.50
DELTA_MIN = 0.12 
DELTA_MAX = 0.30
YIELD_MIN = 0.05
YIELD_MAX = 1.00
EXPIRATION_MIN = 35
EXPIRATION_MAX = 55
OPEN_INTEREST_MIN = 100
SCORE_MIN = 0.05

# --- ADVANCED RISK FILTERS ---
MAX_BID_ASK_SPREAD = 1.50   # Hard cap in dollars
MAX_RELATIVE_SPREAD = 0.15  # Dynamic cap (15% of option value)
MAX_SPREADS_PER_SYMBOL = 1
MAX_NEW_TRADES_PER_CYCLE = 8

# 0.98 means we ask for 98% of the mid-price (giving the market maker 2% incentive to fill us).
SLIPPAGE_ALLOWANCE = 0.0  
# SLIPPAGE_ALLOWANCE = 1.0: Purely dynamic (trusts the bot 100%).

# SLIPPAGE_ALLOWANCE = 0.90: Makes the bot 10% more aggressive to get fills.

# SLIPPAGE_ALLOWANCE = 1.10: Makes the bot 10% greedier (demands better prices).

AVOID_EARNINGS = True
MAX_RISK_PER_SPREAD = 1000.0  
PROFIT_TARGET = 0.50  
STOP_LOSS = 3.0

# --- FUND DASHBOARD SETTINGS ---

# 1. Discord Alerts (Create a free Discord server, go to Channel Settings -> Integrations -> Webhooks, and paste the URL here)
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1483972575238426717/J5yYPUhtiwOzs9bXTFwOypf-0SfqBvBK-ogerhd21Vfx7vrsR6ftnP5w1-Atd383Q36C" # e.g., "https://discord.com/api/webhooks/12345/abcde"

# 2. Idle Cash Sweep
SWEEP_TICKER = "SGOV"  # SGOV = 0-3 Month Treasury Bill ETF (~5.3% Yield)
TARGET_CASH_BUFFER = 1000.0 # Always keep at least $1,000 in pure cash for daily settlements

# 3. Dynamic VIX Risk Scaling
MAX_RISK_BASE = 1000.0 # Your standard risk when VIX is normal

# 4. Signal Quality Guardrails
# Avoid forcing full deployment when the directional models disagree or are weak.
MIN_SIGNAL_CONFIDENCE = 0.18
LOW_CONFIDENCE_RISK_MULTIPLIER = 0.50

# 5. HMM pairs mean-reversion overlay
ENABLE_PAIRS_TRADING = True
PAIR_MAX_SIGNALS = 6
PAIR_ENTRY_ZSCORE = 1.5
PAIR_LOOKBACK_DAYS = 120
PAIR_MIN_CORRELATION = 0.65
PAIR_MIN_CONFIDENCE = 0.55

# 6. Execution quality / TCA knobs
TCA_SPREAD_WEIGHT = 0.65
TCA_SLIPPAGE_WEIGHT = 0.25
TCA_LIQUIDITY_WEIGHT = 0.10

# 6B. Delay-aware option repricing controls
OPTION_QUOTE_DELAY_MINUTES = 15
OPTION_PRICING_RISK_FREE_RATE = 0.04
OPTION_DELAY_MIN_PRICING_CONFIDENCE = 0.32
OPTION_DELAY_MAX_UNDERLYING_MOVE_PCT = 0.035
OPTION_DELAY_QUOTE_HAIRCUT = 0.06

# 6C. Cross-sectional ML alpha controls
ML_ALPHA_ENABLED = True
ML_ALPHA_MAX_SYMBOLS = 48
ML_ALPHA_MIN_TRAIN_MONTHS = 48
ML_ALPHA_CACHE_MAX_AGE_MINUTES = 240
ML_ALPHA_TOP_PERCENTILE = 0.80
ML_ALPHA_BOTTOM_PERCENTILE = 0.20

# 7. Platinum-mode portfolio sizing controls
PLATINUM_MODE = True
TARGET_DAILY_RETURN_GOAL = 0.05  # Stretch target; not a guarantee.
MAX_KELLY_FRACTION = 0.35

# 8. Direct equity overlay controls
ENABLE_EQUITY_OVERLAY = True
EQUITY_OVERLAY_MAX_ALLOCATION = 0.12
EQUITY_OVERLAY_MAX_POSITIONS = 4
EQUITY_OVERLAY_MAX_SYMBOL_WEIGHT = 0.04
EQUITY_OVERLAY_MIN_SIGNAL = 0.62
EQUITY_OVERLAY_EXIT_SIGNAL = 0.52
EQUITY_OVERLAY_MIN_EXPECTED_MOVE = 0.0005
EQUITY_OVERLAY_PROFIT_TARGET = 0.08
EQUITY_OVERLAY_STOP_LOSS = 0.05
EQUITY_OVERLAY_MAX_VIX = 26.0

# 9. Direct equity event / IV / distribution filters
EQUITY_OVERLAY_EVENT_WINDOW_DAYS = 10
EQUITY_OVERLAY_MAX_EVENT_CANDIDATES = 8
EQUITY_OVERLAY_MAX_IV_RANK = 80.0
EQUITY_OVERLAY_IV_FLOOR_RANK = 30.0
EQUITY_OVERLAY_MAX_IV_REALIZED_RATIO = 1.35
EQUITY_OVERLAY_MAX_DISTRIBUTION_ZSCORE = 1.8
EQUITY_OVERLAY_EVENT_BOOST = 0.08

# 10. Stock-based delta hedge overlay
ENABLE_DELTA_HEDGE_OVERLAY = True
DELTA_HEDGE_LONG_SYMBOL = "SPY"
DELTA_HEDGE_INVERSE_SYMBOL = "SH"
DELTA_HEDGE_MAX_ALLOCATION = 0.08
DELTA_HEDGE_MIN_GAP = 20.0
DELTA_HEDGE_SCALING = 0.75
DELTA_HEDGE_MAX_VIX = 32.0
